# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "FLCos"
description: > # this means to ignore newlines until "email:"
   Fast,Light,controlling system

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/flcos_logo.jpg"
# blog cover
cover: "/assets/images/background.jpg"

name: 'Allen Li'
author: 'Allen Li'
author_image: "/assets/images/author.jpg"

paginate:	8

url: "https://flcos.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@lhf552004'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/lhf552004
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/lhf552004
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
